# Generated by Django 5.0.7 on 2026-06-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_revenuerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='kind',
            field=models.CharField(choices=[('ayo', 'AYO'), ('whatsapp', 'WhatsApp'), ('walk_in', 'Walk In'), ('member', 'Member')], default='walk_in', max_length=16),
        ),
    ]
