# Generated by Django 5.0.7 on 2026-06-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_booking_note_alter_booking_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='jam_terpilih',
            field=models.CharField(default='[]', help_text='Contoh: [6, 7, 8]', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
