# Generated by Django 5.0.7 on 2026-06-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_booking_jam_terpilih_alter_booking_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='image_proof',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_proofs/'),
        ),
    ]
