# Generated by Django 5.0.7 on 2026-06-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_shift_image_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='sickleave',
            name='medical_proof',
            field=models.ImageField(blank=True, null=True, upload_to='sick_leaves/'),
        ),
    ]
